# Railway Configuration
# Docs: https://docs.railway.app/deploy/config-as-code

[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "backend"
source = "backend"

[services.healthcheck]
path = "/api/health"
timeout = 100

# Frontend Service
[[services]]
name = "frontend"  
source = "frontend"

[services.build]
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npx serve dist -l 3000"

