# Render Blueprint để deploy Spotify Clone
# Docs: https://render.com/docs/blueprint-spec

services:
  # Backend Service
  - type: web
    name: spotify-backend
    runtime: node
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Nhập thủ công trên dashboard
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: CLERK_PUBLISHABLE_KEY
        sync: false  # Nhập từ Clerk dashboard
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Nhập từ Cloudinary dashboard
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /api/health

  # Frontend Service  
  - type: web
    name: spotify-frontend
    runtime: static
    region: singapore
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

